# Generated by Django 3.2.4 on 2021-06-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_perfume_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntuacion',
            old_name='perfume',
            new_name='perfume_id',
        ),
        migrations.RenameField(
            model_name='puntuacion',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
